### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by xavriley** [jakobabesser/bassunet#1]
It looks like the `conda_env.yml` file needs an update. To get this working I found I had to do the the following:

```
conda create --name bassunet python="3.6"
conda activate bassunet
pip install librosa tensorflow==1.15 "h5py<3.0.0"
```

The `h5py` is due to a bug with the latest versions breaking loading of Keras models, described here: https://github.com/tensorflow/tensorflow/issues/44467#issuecomment-719964088

Otherwise this is all working for me 👍

**Comment by jakobabesser** [comment]
Thank you @xavriley, I adopted you code in the `README` and removed the obsolete conda environment file.
